// - imdbId: optional — the "tt" number from the IMDb URL (e.g. imdb.com/title/tt0068646)
//           if omitted, the script will look it up by name automatically
// - type:   "movie" or "series"

export const addItems = [
  // { name: "Example Movie", type: "movie" },

  { name: "20th Century Girl", type: "movie" },
  { name: "I Saw the Devil", type: "movie" },
  { name: "Love Reset", type: "movie" },
  { name: "Omniscient Reader: The Prophecy", type: "movie" },
  { name: "Silenced", type: "movie" },
  { name: "Soulmate", type: "movie" },
  { name: "A Good Day to Be a Dog", type: "series" },
  { name: "A Korean Odyssey", type: "series" },
  { name: "Are You Human?", type: "series" },
  { name: "As You Stood By", type: "series" },
  { name: "Because This Is My First Life", type: "series" },
  { name: "Black", type: "series" },
  { name: "Brewing Love", type: "series" },
  { name: "Bring It On, Ghost", type: "series" },
  { name: "Bulgasal: Immortal Souls", type: "series" },
  { name: "Business Proposal", type: "series" },
  { name: "Cheer Up", type: "series" },
  { name: "Cringy Romance", type: "series" },
  { name: "Daily Dose of Sunshine", type: "series" },
  { name: "Death's Game", type: "series" },
  { name: "Delightfully Deceitful", type: "series" },
  { name: "Descendants of the Sun", type: "series" },
  { name: "Destined with You", type: "series" },
  { name: "Doom at Your Service", type: "series" },
  { name: "Dr. Romantic", type: "series" },
  { name: "Flower of Evil", type: "series" },
  { name: "Friendly Rivalry", type: "series" },
  { name: "From Now On, Showtime!", type: "series" },
  { name: "Gangnam B-Side", type: "series" },
  { name: "He Is Psychometric", type: "series" },
  { name: "Head over Heels", type: "series" },
  { name: "Healer", type: "series" },
  { name: "Her Private Life", type: "series" },
  { name: "Idol I", type: "series" },
  { name: "Inspector Koo", type: "series" },
  { name: "It's Okay to Not Be Okay", type: "series" },
  { name: "Kill It", type: "series" },
  { name: "Love Alarm", type: "series" },
  { name: "Love Next Door", type: "series" },
  { name: "Love Scout", type: "series" },
  { name: "Mad Dog", type: "series" },
  { name: "Melo Movie", type: "series" },
  { name: "Misaeng: Incomplete Life", type: "series" },
  { name: "Missing: The Other Side", type: "series" },
  { name: "Moon in the Day", type: "series" },
  { name: "Move to Heaven", type: "series" },
  { name: "Moving", type: "series" },
  { name: "Mr. Plankton", type: "series" },
  { name: "My Mister", type: "series" },
  { name: "My Youth", type: "series" },
  { name: "No Tail to Tell", type: "series" },
  { name: "Our Beloved Summer", type: "series" },
  { name: "Our Unwritten Seoul", type: "series" },
  { name: "Perfect Crown", type: "series" },
  { name: "Perfect Family", type: "series" },
  { name: "Queen of Tears", type: "series" },
  { name: "Reply 1988", type: "series" },
  { name: "Second Shot at Love", type: "series" },
  { name: "See You in My 19th Life", type: "series" },
  { name: "SF8", type: "series" },
  { name: "Sh**ting Stars", type: "series" },
  { name: "She Would Never Know", type: "series" },
  { name: "Single's Inferno", type: "series" },
  { name: "Spring of Youth", type: "series" },
  { name: "Start-Up", type: "series" },
  { name: "Strong Girl Bong Soon", type: "series" },
  { name: "Suspicious Partner", type: "series" },
  { name: "SynchroU", type: "series" },
  { name: "Taxi Driver", type: "series" },
  { name: "The Atypical Family", type: "series" },
  { name: "The Beauty Inside", type: "series" },
  { name: "The Glory", type: "series" },
  { name: "The K2", type: "series" },
  { name: "The Manipulated", type: "series" },
  { name: "The Producers", type: "series" },
  { name: "The Smile Has Left Your Eyes", type: "series" },
  { name: "The Story of Park's Marriage Contract", type: "series" },
  { name: "True Beauty", type: "series" },
  { name: "Twinkling Watermelon", type: "series" },
  { name: "Two Cops", type: "series" },
  { name: "W", type: "series" },
  { name: "When Life Gives You Tangerines", type: "series" },
  { name: "Would You Marry Me?", type: "series" },
];

export const removeItems = [
  // { name: "Example Movie", type: "movie" },
];
